### ISSUE TITLE
how to run jquery with https

### ISSUE THREAD

**Issue by directorscut82** [ShockwaveNN/feedly-to-pocket#1]
Thank you for your script!
However i encountered various errors trying to switch off ssl and after posting to jquery forum i found a solution (i post the link in case you r interested): 

https://forum.jquery.com/topic/export-“saved-for-later”-from-evil-feedly

**Comment by ShockwaveNN** [comment]
Hi there. Sorry to inform you (I should add this to readme file), but I stop develped this project. 
Instead I forked https://github.com/turadg/pocket-ruby to add ability to upload custom json files - you should watch my another project https://github.com/ShockwaveNN/pocket-sinatra-interface
And I fix your problems in there now
